# Node docker image on which this would be run
image: node:8.9.0

stages:
  - test
  - deploy

#eslint:
#  stage: lint
#  script:
#    # Install eslint
#    - |
#      npm install eslint \
#      eslint-config-standard
#    # Run eslint
#    - node_modules/eslint/bin/eslint.js .

testreact:
  stage: test
  script:
    - yarn
    - yarn test

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash deploy/deploy.sh
